# Setup
title:               Bryanomics
tagline:             'economics & beyond'
description:         'Your simple guide to understanding economics in everyday life.'
url:                 https://bryanomics.org
baseurl:             ''
paginate:            5
permalink:           /:title
# About/contact
author:
  name:              Bryanomics
  url:               https://bryanomics.org
  email:             bryanomics@outlook.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0
google_analytics_id: #UA-XXXX-Y
